### ISSUE TITLE
Separation to `CheckedArithmeticCore`

### ISSUE THREAD

**Issue by kimikage** [JuliaMath/CheckedArithmetic.jl#6]
From the beginning of this package, I have believed that the dependencies on this package would bring in trouble. (cf. https://github.com/JuliaMath/FixedPointNumbers.jl/pull/146#issuecomment-560099028)

The "features" provided by `CheckedArithmetic` are on a higher level than packages that provide types like `FixedPointNumbers`. The dependency of a low-level package on a high-level package leads to roughly two problems.
1. Keeping up with compatibility
Until `CheckedArithmetic` reaches v1.0, packages that provide numeric types are implicitly required to keep up with the new version when there are changes to the implementation or functionality of `CheckedArithmetic`, even if they do not break the existing API.

2. Weight limit of `CheckedArithmetic`
If `CheckedArithmetic` is "heavy", it affects all users of the package which (indirectly) depend on the package providing the numeric types. Therefore, `CheckedArithmetic` is implicitly required to be lightweight. I suspect that the `Cassette`'s injection feature could be useful in "end-user" code, but I don't think it is a good idea for packages which provide numeric types to be dependent on `Cassette`.

I would like to make the `CheckedArithmetic` support not only `checked` arithmetic, but also `wrapping` and `saturating` arithmetic. (cf. https://github.com/JuliaMath/FixedPointNumbers.jl/issues/152#issuecomment-647113657) And in the future, I would like to integrate the features into `Base`(`Base.Checked`). With this perspective, I think it would be beneficial to make the APIs and the implementations separate.

**Comment by timholy** [comment]
I approve of this plan.

**Comment by kimikage** [comment]
It's debatable as to which scope should be moved to the `CheckedArithmeticCore`.
1. function definitions
2. fallback implementations with `Any`
3. implementations for `Base` types
4. implementations for "stdlib" types

I think 1. and 2. should be in `CheckedArithmeticCore`; 3. and 4. could be included as well, but I have some questions about the current implementations. For example:
https://github.com/JuliaMath/CheckedArithmetic.jl/blob/50243f08841b12d8b207f78672fc776c97ef4495/src/CheckedArithmetic.jl#L144
